let nome = "(larissa)"
let email = "(lari.cissa@hotmail.com)"
let profissao = "(administradora)"
let idade = "(26)"
let lugar = "(Peru)"
string = nome
string = email
string = profissao
string = idade
string = lugar
